language: ruby

rvm:
 - 2.4
 - 2.5
 - 2.6
 - 2.7

gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_latest_and_doorkeeper_latest.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/rails_latest_and_doorkeeper_latest.gemfile
